# Generated by Django 5.2.17 on 2026-09-25 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('key_observations', models.JSONField(blank=True, default=list)),
                ('abnormal_values', models.JSONField(blank=True, default=list)),
                ('simple_explanations', models.JSONField(blank=True, default=list)),
                ('doctor_questions', models.JSONField(blank=True, default=list)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=150)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=30)),
                ('reference_range', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal'), ('LOW', 'Low'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='documents.documentanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='HealthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('BLOOD_TEST', 'Blood Test'), ('CBC', 'CBC'), ('LIPID_PROFILE', 'Lipid Profile'), ('DIABETES_TEST', 'Diabetes Test'), ('THYROID_TEST', 'Thyroid Test'), ('LIVER_FUNCTION', 'Liver Function Test'), ('KIDNEY_FUNCTION', 'Kidney Function Test'), ('PRESCRIPTION', 'Prescription'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('file', models.FileField(upload_to='health_documents/')),
                ('document_date', models.DateField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('analysis_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('ANALYZED', 'Analyzed'), ('FAILED', 'Failed')], default='PENDING', max_length=15)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentanalysis',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='documents.healthdocument'),
        ),
    ]
