# Generated by Django 5.2.17 on 2026-09-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedtestresult',
            name='reference_high',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractedtestresult',
            name='reference_low',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
